### ISSUE TITLE
whentrain faster-rnn inited from pretrained model on imagenet, why set `FREEZE_CONV_BODY_AT: 0`?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [vov-net/VoVNet-Detectron#1]
whentrain faster-rnn inited from pretrained model on imagenet, why set `FREEZE_CONV_BODY_AT: 0`?

**Comment by stigma0617** [comment]
@zimenglan-sysu-512,

`FREEZE_CONV_BODY_AT: 0` shows better performance than  `FREEZE_CONV_BODY_AT: 2`.
