### ISSUE TITLE
testing e2e_mask_rcnn_V_39_FPN_2x.yaml get low mAP

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [vov-net/VoVNet-Detectron#2]
hi @stigma0617 
when i test the `e2e_mask_rcnn_V_39_FPN_2x.yaml` using the trained model from provided link, it only get `0.005` for bbox and `0.005` for mask. it seems that it miss some weights from the `stem`.

**Comment by stigma0617** [comment]
@zimenglan-sysu-512 
thanks for pointing out.

I update the download link.

If you face the same problem, feel free to re-open this issue.
