### ISSUE TITLE
when export using onnx, the ceil_mode does not work

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [vov-net/VoVNet-Detectron#3]
hi @stigma0617 
when i try to export the trained model using onnx, and find that the [ceil_mode](https://github.com/vov-net/VoVNet-Detectron/blob/master/maskrcnn_benchmark/modeling/backbone/vovnet.py#L131) does not work. is there a way to change it for supporting onnx?
thanks

**Comment by stigma0617** [comment]
@zimenglan-sysu-512 

I don't know the exact alternative solution for ceil_mode because ceil_mode of pooling layer is the internal function of pytorch library. 

I'm sorry I couldn't help you.

Let me know if you find a suitable solution.

**Comment by zimenglan-sysu-512** [comment]
hi @stigma0617 
i change the `ceil_mode` to False, and add `padding=1`, and then retrain the model, find that the result is the same as using `ceil_mode=True`
